#!/bin/sh

CFILE="./classes.md"

echo "Список классов PF 2" > $CFILE
echo "===================" >> $CFILE
echo  >> $CFILE
echo "[autogenerated]" >> $CFILE

find . -name "*.p" \
   | sort | xargs grep "^@CLASS" -A 1 -H \
   | awk '$0 !~ /(--|@CLASS)/{split($0, m, "-"); if(mod != m[1]){printf("\n### [%s](%s)\n", m[1], m[1])} if(substr(m[2], 1, 2) != "__"){print "*", m[2]; mod = m[1]}} END{ printf("\n"); }' \
   >>$CFILE


