<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>p</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>name</key>
	<string>Parser3</string>
	<key>patterns</key>
	<array>
                <dict>
                    <key>include</key>
                    <string>text.html.basic</string>
                </dict>
		<dict>
			<key>match</key>
			<string>\^(if|for|eval|process|while|s(witch|leep)|c(a(se|che)|on(nect|tinue))|t(aint|hrow|ry)|u(ntaint|se)|apply-taint|break)\b</string>
			<key>name</key>
			<string>keyword.operator.parser3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\^#[0-9a-fA-F]{2}</string>
			<key>name</key>
			<string>constant.character.parser3</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\^rem\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rem-insider</string>
				</dict>
			</array>
			<key>name</key>
			<string>comment.block.parser3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^#.*</string>
			<key>name</key>
			<string>comment.line.parser3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\^)(\^|\$|;|@|\(|\)|\{|\}|\[|\]|:|"|'|#)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.parser3</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\^[\w\-]+::[\w\-]*\b</string>
			<key>name</key>
			<string>entity.name.function.constructor.parser3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$result\b(?![-_.:])</string>
			<key>name</key>
			<string>variable.language.result.parser3</string>
		</dict>


		<dict>
			<key>match</key>
			<string>^@[\w\-&lt;&gt;\*/]*$</string>
			<key>name</key>
			<string>entity.name.function.parser3</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(@[\w\-*/&lt;&gt;\.]+)(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.definition.parser3</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.string.parser3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])?(\s.*)?$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.string.parser3</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.parser3</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.definition.parser3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#separator</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\]\[</string>
					<key>name</key>
					<string>punctuation.section.string.parser3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bresult\b</string>
					<key>name</key>
					<string>variable.parameter.result.parser3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\blocals\b</string>
					<key>name</key>
					<string>variable.parameter.locals.parser3</string>
				</dict>
			</array>
		</dict>


		<dict>
			<key>begin</key>
			<string>\^[\w\-/\*&lt;&gt;]*</string>
			<key>end</key>
			<string>((?![.:])|\s)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.parser3</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.definition.parser3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\.|:)(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.parser3</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.string.parser3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.string.parser3</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
					<key>name</key>
					<string>meta.parameters.parser3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\.|:)(\$[\w\-]*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.parser3</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.parser3</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(\.|:)[\w\-/\*&lt;&gt;]*</string>
					<key>name</key>
					<string>entity.name.function.parser3</string>
				</dict>
			</array>
		</dict>


		<dict>
			<key>name</key>
			<string>meta.variable.definition.parser3</string>
			<key>begin</key>
			<string>(\$)(\{)(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.parser3</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.code.parser3</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.parser3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.code.parser3</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-branch</string>
				</dict>
			</array>
		</dict>

		<dict>
			<key>name</key>
			<string>meta.variable.definition.parser3</string>
			<key>begin</key>
			<string>\$\.?[\$\w\-]*</string>
			<key>end</key>
			<string>(\b(?![.:])|\B(?![\w\-\$])|\s)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.other.parser3</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-branch</string>
				</dict>
			</array>
		</dict>



		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>(\)|\n(?=^@))</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.expression.parser3</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#separator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quoted-string-single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quoted-string-double</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)((e|E)(\+|-)?[0-9]+)?))\b</string>
					<key>name</key>
					<string>constant.numeric.parser3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(true|false)\b</string>
					<key>name</key>
					<string>constant.language.parser3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(is|def|in|ne|eq|lt|gt|le|ge)\b</string>
					<key>name</key>
					<string>keyword.operator.parser3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\B(-f|-d)\b</string>
					<key>name</key>
					<string>keyword.operator.parser3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[-!%&amp;&lt;&gt;*+=/\\~|]</string>
					<key>name</key>
					<string>keyword.operator.symbolic.parser3</string>
				</dict>
			</array>
			<key>name</key>
			<string>meta.expression.parser3</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.string.parser3</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#separator</string>
				</dict>
			</array>
			<key>name</key>
			<string>meta.string.parser3</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.code.parser3</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#separator</string>
				</dict>
			</array>
			<key>name</key>
			<string>meta.code.parser3</string>
		</dict>

		
	</array>

	<key>repository</key>
	<dict>
		<key>separator</key>
		<dict>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>punctuation.separator.parser3</string>
		</dict>
		<key>rem-insider</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rem-insider</string>
				</dict>
			</array>
		</dict>
		<key>quoted-string-single</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.parser3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>quoted-string-double</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.parser3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>variable-inline</key>
		<dict>
			<key>begin</key>
			<string>(\.|:)(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.parser3</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.string.parser3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.string.parser3</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>name</key>
			<string>meta.parameters.parser3</string>
		</dict>
		<key>variable-branch</key>
		<dict>
			<key>match</key>
			<string>[.:]\$?[\w\-]*</string>
			<key>name</key>
			<string>variable.other.parser3</string>
		</dict>		
	</dict>

	<key>scopeName</key>
	<string>source.parser3</string>
	<key>uuid</key>
	<string>AF64B54B-CA02-4B85-9D8E-898CD3FF98C8</string>
</dict>
</plist>